export const companyInfo = {
  name: 'Sikka Engineering Pvt. Limited',
  shortName: 'Bharat E&IL',
  tagline: 'Engineering Excellence Built on Trust & Innovation',
  description: 'Leading engineering, infrastructure and project execution partner serving government and private sectors across India.',
  phone: '91 98992 46485',
  email: 'info@secpl.org',
  address: 'H- 14/16 Malviya Nagar, New Delhi-110017',
  linkedin: 'https://linkedin.com/company/bharat-engineering',
  founded: 2004,
  employees: 350,
  projects: 100,
  clients: 100,
  cities: 25,
  engineers: 50,
};

export const services = [
  {
    id: 'engineering-consultancy',
    title: 'Engineering Consultancy',
    description: 'Comprehensive engineering consulting services for infrastructure, industrial, and government projects including feasibility studies, design, and technical advisory.',
    icon: 'Compass',
  },
  {
    id: 'infrastructure-development',
    title: 'Infrastructure Development',
    description: 'End-to-end infrastructure development for roads, bridges, highways, railways, and urban infrastructure with strict quality and timeline adherence.',
    icon: 'Building2',
  },
  {
    id: 'project-management',
    title: 'Project Management',
    description: 'Expert project management services ensuring cost control, quality assurance, risk management, and timely delivery for complex engineering projects.',
    icon: 'ClipboardList',
  },
  {
    id: 'industrial-construction',
    title: 'Industrial Construction',
    description: 'Specialized industrial construction for factories, warehouses, power plants, and processing facilities with advanced engineering solutions.',
    icon: 'Factory',
  },
  {
    id: 'mep-solutions',
    title: 'MEP Solutions',
    description: 'Mechanical, Electrical, and Plumbing solutions for commercial, industrial, and institutional buildings with sustainable design practices.',
    icon: 'Zap',
  },
  {
    id: 'government-contracts',
    title: 'Government Contract Execution',
    description: 'Proven track record in executing government tenders, PSU projects, and public infrastructure with full regulatory compliance and transparency.',
    icon: 'Landmark',
  },
];

// export const projects = [
//   {
//     id: 'nh-44-widening',
//     title: 'NH-44 Highway Widening',
//     category: 'Infrastructure',
//     location: 'Delhi - Agra, Uttar Pradesh',
//     client: 'National Highways Authority of India',
//     cost: 'INR 1,250 Crores',
//     status: 'Completed',
//     image: 'https://images.unsplash.com/photo-1519817914152-22d216bb9170?w=800&h=500&fit=crop',
//     description: 'Four-laning of NH-44 from Delhi to Agra covering 200 km with modern road infrastructure, bridges, and toll systems.',
//   },
//   {
//     id: 'metro-corridor',
//     title: 'Metro Rail Corridor Phase II',
//     category: 'Government',
//     location: 'Mumbai, Maharashtra',
//     client: 'Mumbai Metro Rail Corporation',
//     cost: 'INR 890 Crores',
//     status: 'Ongoing',
//     image: 'https://images.unsplash.com/photo-1545987796-200677ee1011?w=800&h=500&fit=crop',
//     description: 'Underground metro corridor construction including stations, tunnels, and integrated transit systems for urban connectivity.',
//   },
//   {
//     id: 'thermal-power',
//     title: 'Thermal Power Plant Unit',
//     category: 'Industrial',
//     location: 'Singrauli, Madhya Pradesh',
//     client: 'NTPC Limited',
//     cost: 'INR 2,100 Crores',
//     status: 'Completed',
//     image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=500&fit=crop',
//     description: '660 MW thermal power plant unit construction including boiler, turbine, generator installation, and auxiliary systems.',
//   },
//   {
//     id: 'smart-city',
//     title: 'Smart City Infrastructure',
//     category: 'Utilities',
//     location: 'Indore, Madhya Pradesh',
//     client: 'Indore Smart City Development',
//     cost: 'INR 450 Crores',
//     status: 'Ongoing',
//     image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=500&fit=crop',
//     description: 'Smart city infrastructure development including fiber optic network, smart lighting, surveillance, and integrated command center.',
//   },
//   {
//     id: 'railway-bridge',
//     title: 'Major Railway Bridge',
//     category: 'Infrastructure',
//     location: 'Patna, Bihar',
//     client: 'Indian Railways',
//     cost: 'INR 380 Crores',
//     status: 'Completed',
//     image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=500&fit=crop',
//     description: 'Construction of a major railway bridge over the Ganges river including approach viaducts and modern signaling systems.',
//   },
//   {
//     id: 'water-treatment',
//     title: 'Water Treatment Plant',
//     category: 'Utilities',
//     location: 'Hyderabad, Telangana',
//     client: 'Hyderabad Metropolitan Water Supply',
//     cost: 'INR 220 Crores',
//     status: 'Completed',
//     image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&h=500&fit=crop',
//     description: '150 MLD capacity water treatment plant with advanced filtration, chlorination, and distribution network infrastructure.',
//   },
// ];

export const projects = [
  {
    id: 'laksar-electrification',
    title: 'Electrification of Laksar-Haridwar-Raiwala-Dehradun Section',
    category: 'Railway Electrification',
    location: 'Laksar-Haridwar-Raiwala-Dehradun, Moradabad Division',
    client: 'Indian Railways',
    cost: '₹21.82 Crores',
    status: 'Completed',
    image: 'https://images.unsplash.com/photo-1519817914152-22d216bb9170?w=800&h=500&fit=crop',
    description: 'Including provision of 3 SSPs & Design, Supply, Erection, Testing & Commissioning of 25kV AC single phase OHE for Doubling including Modification of SP at Pathri, SSP at Laksar and TSS at Jawalapur of Laksar-Haridwar Section of Moradabad Division. Technical: 117.44 TKM OHE & SP/SSP',
  },
  {
    id: 'panvel-electrification',
    title: 'Panvel – Pen Section Electrification',
    category: 'Railway Electrification',
    location: 'Panvel – Pen, Mumbai Division, Central Railway',
    client: 'Indian Railways',
    cost: '₹26.99 Crores',
    status: 'Completed',
    image: 'https://images.unsplash.com/photo-1545987796-200677ee1011?w=800&h=500&fit=crop',
    description: 'Design, Supply, Erection, Testing and Commissioning of 25kV AC, single phase 50 Hz regulated Overhead Equipment in Panvel (Excl.) – Pen (Excl.) section of Mumbai division of Central Railway. Technical: 73.5 TKM OHE',
  },
  {
    id: 'najibabad-electrification',
    title: 'Najibabad-Kotdwar & Raiwala-Rishikesh Section Electrification',
    category: 'Railway Electrification',
    location: 'Najibabad-Kotdwar & Raiwala-Rishikesh, Moradabad Division',
    client: 'Indian Railways',
    cost: '₹15.21 Crores',
    status: 'Completed',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&h=500&fit=crop',
    description: 'Design, Supply, Erection, Testing & Commissioning of 25kV AC single phase OHE for Najibabad-Kotdwar Section including 3 SSPs and Raiwala-Rishikesh Section including 1 SSP and modification in SSP at Raiwala over Moradabad Division. Technical: 49.368 TKM OHE & SP/SSP',
  },
  {
    id: 'barhan-ohe',
    title: 'Barhan-Etah Section OHE Work',
    category: 'Railway OHE',
    location: 'Barhan-Etah, Allahabad Division, N.C. Railway',
    client: 'Indian Railways',
    cost: '₹26.54 Crores',
    status: 'Completed',
    image: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800&h=500&fit=crop',
    description: 'Design, Supply, Erection and Testing & Commissioning of 25kV 50Hz, AC "OHE" of Barhan-Etah Section (65 Km) of Allahabad Division of N.C. Railway. Technical: 77.803 TKM OHE',
  },
  {
    id: 'khatauli-doubling',
    title: 'Khatauli to Muzaffarnagar Patch Doubling',
    category: 'Railway Doubling',
    location: 'Khatauli-Muzaffarnagar-Devbandh, Lucknow Division',
    client: 'Indian Railways',
    cost: '₹14.60 Crores',
    status: 'Completed',
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=500&fit=crop',
    description: 'Electrification work of Khatauli to Muzaffarnagar section patch doubling and Muzaffarnagar to Devbandh doubling including Modification of SP at Janghai and SP at Suriawan of Bhadohi-Janghai section of Lucknow division. Technical: 24.522 TKM OHE & 40 TKM OHE & SP/SSP',
  },
  {
    id: 'bhadohi-doubling',
    title: 'Bhadohi-Janghai Section Doubling',
    category: 'Railway Doubling',
    location: 'Bhadohi-Janghai, Lucknow Division',
    client: 'Indian Railways',
    cost: '₹22.71 Crores',
    status: 'Completed',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&h=500&fit=crop',
    description: 'Design, Supply, Erection, Testing & Commissioning of 25kV AC single phase OHE for doubling including Modification of SP at Chaukhandi, SSP at Kapsheti and FP at Lohta – Bhadoi Section of Lucknow Division. Technical: 54 TKM OHE & SP/SSP',
  },
];

// export const industries = [
//   {
//     id: 'government',
//     title: 'Government Sector',
//     description: 'Executing government tenders, PSU projects, and public infrastructure with full regulatory compliance and transparency.',
//     icon: 'Landmark',
//   },
//   {
//     id: 'infrastructure',
//     title: 'Infrastructure',
//     description: 'Roads, highways, bridges, railways, and urban infrastructure development for public and private clients.',
//     icon: 'Route',
//   },
//   {
//     id: 'manufacturing',
//     title: 'Manufacturing',
//     description: 'Industrial facility construction for manufacturing plants, assembly units, and production facilities.',
//     icon: 'Cog',
//   },
//   {
//     id: 'industrial',
//     title: 'Industrial',
//     description: 'Power plants, refineries, chemical plants, and heavy industrial infrastructure construction.',
//     icon: 'Factory',
//   },
//   {
//     id: 'energy',
//     title: 'Energy',
//     description: 'Thermal, solar, and renewable energy projects with advanced engineering and sustainable practices.',
//     icon: 'Sun',
//   },
//   {
//     id: 'utilities',
//     title: 'Utilities',
//     description: 'Water treatment, sewage systems, power distribution, and urban utility infrastructure projects.',
//     icon: 'Droplets',
//   },
// ];

// export const clients = [
//   'National Highways Authority of India',
//   'Indian Railways',
//   'NTPC Limited',
//   'Bharat Petroleum',
//   'Indian Oil Corporation',
//   'Mumbai Metro Rail Corporation',
//   'Delhi Metro Rail Corporation',
//   'State Bank of India',
//   'Larsen & Toubro',
//   'Tata Projects',
//   'Hindustan Construction',
//   'IRCON International',
//   'RITES Limited',
//   'NBCC India',
//   'Power Grid Corporation',
//   'Bharat Electronics',
// ];
export const industries = [
  {
    id: 'railway',
    title: 'Railway',
    description:
      'Delivering railway infrastructure solutions including track works, station development, electrification support, signaling, and allied civil engineering projects with a strong focus on safety, quality, and timely execution.',
    icon: 'Train',
  },
  {
    id: 'steel',
    title: 'Steel',
    description:
      'Providing structural steel fabrication, erection, industrial sheds, warehouses, plant structures, and customized steel engineering solutions for commercial and industrial projects.',
    icon: 'Factory',
  },
  {
    id: 'energy',
    title: 'Energy',
    description:
      'Executing power and energy infrastructure projects across conventional and renewable sectors, including transmission, substations, solar installations, and sustainable engineering solutions.',
    icon: 'Zap',
  },
];
export const clients = [
  { name: 'Vedanta', logo: 'https://www.vedantalimited.com/img/media_kit/Vedanta_logo_tagline_white_bg.jpg' },
  { name: 'Indian Railways', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4KaxfX4klII8gwXPmhxogwK8HRzUOONOHcyKddWpl-Q&s=10' },
  { name: 'IRCON', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-6Z-jF1x4hrihVEY6BURkWbx1nNcjoZuIqw&s' },
  { name: 'Rail Vikas Nigam Limited', logo: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEieJnzjmr5SiOc2OjU44CN0QfJo0RpxDQjOwUmZA-KtUWthSe6GYyYmt6oss-VfdeGCDmX9nIAjb9Pg9Ymom5DDomevMjvgH18FUNVfCVM_MfNxtHEZTEC46NHrZ8QnX5OKBwVjI4ugFz_xhP3_nfqu1e97HxiS0YyWC2i98y3DpJhZ0fgjOc48S_fP/s386/RVNL.png' },
  { name: 'RITES', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/RITES_green_logo.svg' },
  { name: 'HRIDC', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_tp1tEvB57ruMyVJ4iozTdwYjwmO7VpDapg&s' },
  { name: 'Delhi Metro Rail Corporation', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpgEbIAy5QwNE_FS_YGorEt7EEbma1D0DsxQ&s' },

  // { name: 'Larsen & Toubro', logo: '/logos/lt.png' },
  // { name: 'Tata Projects', logo: '/logos/tata.png' },
  // { name: 'Hindustan Construction', logo: '/logos/hcc.png' },
  // { name: 'IRCON International', logo: '/logos/ircon.png' },
  // { name: 'RITES Limited', logo: '/logos/rites.png' },
  // { name: 'NBCC India', logo: '/logos/nbcc.png' },
  // { name: 'Power Grid Corporation', logo: '/logos/powergrid.png' },
  // { name: 'Bharat Electronics', logo: '/logos/bel.png' },
];

export const certifications = [
  { name: 'ISO 9001:2015', description: 'Quality Management Systems' },
  { name: 'ISO 14001:2015', description: 'Environmental Management Systems' },
  { name: 'ISO 45001:2018', description: 'Occupational Health & Safety' },
  { name: 'CRISIL A1', description: 'Highest Credit Rating for Construction' },
  { name: 'NSIC Registered', description: 'National Small Industries Corporation' },
  { name: 'CPWD Approved', description: 'Central Public Works Department' },
];

export const jobs = [
  {
    id: 'senior-structural-engineer',
    title: 'Senior Structural Engineer',
    department: 'Engineering',
    location: 'Gurugram, Haryana',
    experience: '8-12 Years',
    type: 'Full-time',
    description: 'Lead structural design and analysis for major infrastructure and industrial projects. Proficiency in STAAD.Pro, ETABS, and AutoCAD required.',
    posted: '2 days ago',
  },
  {
    id: 'project-manager-epc',
    title: 'Project Manager - EPC',
    department: 'Project Management',
    location: 'Mumbai, Maharashtra',
    experience: '10-15 Years',
    type: 'Full-time',
    description: 'Manage end-to-end EPC projects from planning to execution. Strong background in government contract execution and large infrastructure projects.',
    posted: '5 days ago',
  },
  {
    id: 'site-engineer-civil',
    title: 'Site Engineer - Civil',
    department: 'Construction',
    location: 'Patna, Bihar',
    experience: '3-6 Years',
    type: 'Full-time',
    description: 'Oversee civil construction activities at site including quality control, safety compliance, and progress monitoring.',
    posted: '1 week ago',
  },
  {
    id: 'quantity-surveyor',
    title: 'Senior Quantity Surveyor',
    department: 'Cost Engineering',
    location: 'Gurugram, Haryana',
    experience: '5-8 Years',
    type: 'Full-time',
    description: 'Prepare BOQs, cost estimates, and tender documents for government and private infrastructure projects.',
    posted: '1 week ago',
  },
  {
    id: 'safety-officer',
    title: 'Safety Officer',
    department: 'HSE',
    location: 'Indore, Madhya Pradesh',
    experience: '4-7 Years',
    type: 'Full-time',
    description: 'Ensure compliance with safety standards at construction sites. NEBOSH certification preferred. Experience in industrial projects.',
    posted: '2 weeks ago',
  },
  {
    id: 'contract-manager',
    title: 'Contract Manager',
    department: 'Contracts & Legal',
    location: 'Gurugram, Haryana',
    experience: '7-10 Years',
    type: 'Full-time',
    description: 'Handle contract negotiations, claims management, and dispute resolution for government and private EPC contracts.',
    posted: '2 weeks ago',
  },
];

export const leadership = [
  {
    name: 'Rajesh Kumar Sharma',
    designation: 'Chairman & Managing Director',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face',
    bio: 'Over 30 years of experience in engineering and infrastructure development. Former Executive Director at a leading PSU.',
  },
  {
    name: 'Dr. Priya Venkatesh',
    designation: 'Director - Technical',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face',
    bio: 'PhD in Civil Engineering from IIT Delhi. 25 years of experience in structural design and project management.',
  },
  {
    name: 'Amitabh Gupta',
    designation: 'Director - Operations',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
    bio: 'Ex-Indian Army Engineer. 22 years of experience in large-scale construction and project execution across India.',
  },
  {
    name: 'Sunita Reddy',
    designation: 'Director - Finance',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
    bio: 'Chartered Accountant with 20 years of experience in corporate finance, taxation, and project funding.',
  },
];

export const timeline = [
  {
    year: '2004',
    title: 'Company Founded',
    description: 'Bharat Engineering & Infrastructure Limited was established in Gurugram with a vision to serve the nation\'s infrastructure needs.',
  },
  {
    year: '2008',
    title: 'First Government Contract',
    description: 'Secured first major government contract for highway construction from NHAI, marking entry into public sector projects.',
  },
  {
    year: '2012',
    title: 'ISO Certifications',
    description: 'Achieved ISO 9001, ISO 14001, and OHSAS 18001 certifications, establishing world-class quality and safety standards.',
  },
  {
    year: '2015',
    title: '500 Crore Revenue Milestone',
    description: 'Crossed annual revenue of INR 500 Crores with projects across 10 states and partnership with major PSUs.',
  },
  {
    year: '2018',
    title: 'Pan-India Expansion',
    description: 'Expanded operations to 25+ cities across India with regional offices in Mumbai, Chennai, Kolkata, and Hyderabad.',
  },
  {
    year: '2022',
    title: 'CRISIL A1 Rating',
    description: 'Achieved highest credit rating for construction companies, reflecting financial strength and project execution capability.',
  },
  {
    year: '2024',
    title: '1000 Crore Order Book',
    description: 'Order book crossed INR 1000 Crores with ongoing government and private infrastructure projects across India.',
  },
];

export const offices = [
  {
    city: 'Corporate Office',
    address: 'H- 14/16 Malviya Nagar, New Delhi-110017',
    phone: '+91 98992 46485',
    email: 'info@secpl.org',
  },
  // {
  //   city: 'Mumbai Office',
  //   address: 'Unit 702, Trade Center, Bandra Kurla Complex, Mumbai, Maharashtra - 400051',
  //   phone: '+91-22-6789-0123',
  //   email: 'mumbai@bharatengineering.com',
  // },
  // {
  //   city: 'Chennai Office',
  //   address: '3rd Floor, Spencers Plaza, Mount Road, Chennai, Tamil Nadu - 600002',
  //   phone: '+91-44-2345-6789',
  //   email: 'chennai@bharatengineering.com',
  // },
  // {
  //   city: 'Kolkata Office',
  //   address: 'Suite 402, Salt Lake City, Sector V, Kolkata, West Bengal - 700091',
  //   phone: '+91-33-2345-6789',
  //   email: 'kolkata@bharatengineering.com',
  // },
];
